DROP DATABASE IF EXISTS HotelReservation;

CREATE DATABASE HotelReservation;

USE HotelReservation;

-- CREATE OCCUPANCY
CREATE TABLE IF NOT EXISTS Occupancy
(OccupancyID INT UNSIGNED AUTO_INCREMENT,
OccupancyMax TINYINT UNSIGNED NOT NULL,
PRIMARY KEY(OccupancyID)
);

-- CREATE ROOM TYPE
CREATE TABLE IF NOT EXISTS RoomType
(TypeID TINYINT UNSIGNED AUTO_INCREMENT,
TypeDesc VARCHAR(20) NOT NULL,
PRIMARY KEY(TypeID)
);

-- CREATE ROOM
CREATE TABLE IF NOT EXISTS Room
(RoomID SMALLINT UNSIGNED AUTO_INCREMENT,
Floor TINYINT UNSIGNED NOT NULL,
RoomNumber SMALLINT UNSIGNED NOT NULL,
OccupancyID INT UNSIGNED NOT NULL,
TypeID TINYINT UNSIGNED NOT NULL,
PRIMARY KEY(RoomID),
CONSTRAINT fk_OccupancyID FOREIGN KEY (OccupancyID) REFERENCES Occupancy(OccupancyID),
CONSTRAINT fk_RoomTypeID FOREIGN KEY (TypeID) REFERENCES RoomType(TypeID)
);

-- CREATE RATE
CREATE TABLE IF NOT EXISTS Rate
(RateID INT UNSIGNED AUTO_INCREMENT,
DayOfYear DATE NOT NULL,
TypeID TINYINT UNSIGNED NOT NULL,
Rate DECIMAL(7,2) UNSIGNED NOT NULL,
PRIMARY KEY(RateID),
CONSTRAINT fk_RateTypeID FOREIGN KEY (TypeID) REFERENCES RoomType(TypeID)
);

-- CREATE AMENITY
CREATE TABLE IF NOT EXISTS Amenity
(AmenityID SMALLINT UNSIGNED AUTO_INCREMENT,
AmenityDesc VARCHAR(30) NOT NULL,
PRIMARY KEY(AmenityID)
);

-- CREATE ROOMAMENITY
CREATE TABLE IF NOT EXISTS RoomAmenity
(RoomID SMALLINT UNSIGNED,
AmenityID SMALLINT UNSIGNED,
Quantity TINYINT UNSIGNED NOT NULL,
PRIMARY KEY(RoomID,AmenityID),
CONSTRAINT fk_RoomID FOREIGN KEY (RoomID) REFERENCES Room(RoomID),
CONSTRAINT fk_AmenityID FOREIGN KEY (AmenityID) REFERENCES Amenity(AmenityID)
);

-- CREATE PROMOTION
CREATE TABLE IF NOT EXISTS Promotion
(PromotionID SMALLINT UNSIGNED AUTO_INCREMENT,
Discount DECIMAL(7,2) UNSIGNED NOT NULL,
BeginDate DATE NOT NULL,
EndDate DATE NOT NULL,
PRIMARY KEY(PromotionID)
);

-- CREATE ADDON
CREATE TABLE IF NOT EXISTS AddOn
(AddOnID SMALLINT UNSIGNED AUTO_INCREMENT,
AddOnDesc VARCHAR(30) NOT NULL,
Fee DECIMAL(7,2) UNSIGNED NOT NULL,
PRIMARY KEY(AddOnID)
);

-- CREATE CUSTOMER
CREATE TABLE IF NOT EXISTS Customer
(CustomerID INT UNSIGNED AUTO_INCREMENT,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Phone VARCHAR(15) NOT NULL,
Email VARCHAR(30),
PRIMARY KEY(CustomerID)
);

-- CREATE RESERVATION
CREATE TABLE IF NOT EXISTS Reservation
(ReservationID INT UNSIGNED AUTO_INCREMENT,
BeginDate DATE NOT NULL,
EndDate DATE NOT NULL,
CustomerID INT UNSIGNED NOT NULL,
PromotionID SMALLINT UNSIGNED,
Cancel BOOL NOT NULL DEFAULT 0,
PRIMARY KEY(ReservationID),
CONSTRAINT fk_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
CONSTRAINT fk_PromotionID FOREIGN KEY (PromotionID) REFERENCES Promotion(PromotionID)
);

-- CREATE ROOMADDON
CREATE TABLE IF NOT EXISTS RoomAddOn
(ReservationID INT UNSIGNED,
RoomID SMALLINT UNSIGNED,
AddOnID SMALLINT UNSIGNED,
ServiceDate DATETIME,
PRIMARY KEY(ReservationID,RoomID,AddOnId,ServiceDate),
CONSTRAINT fk_AddOnReservationID FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID),
CONSTRAINT fk_AddOnRoomID FOREIGN KEY (RoomID) REFERENCES Room(RoomID),
CONSTRAINT fk_AddOnAddOnID FOREIGN KEY (AddOnID) REFERENCES AddOn(AddOnID)
);

-- CREATE GUEST
CREATE TABLE IF NOT EXISTS Guest
(GuestID INT UNSIGNED AUTO_INCREMENT,
ReservationID INT UNSIGNED NOT NULL,
RoomID SMALLINT UNSIGNED NOT NULL,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Age TINYINT UNSIGNED NOT NULL,
PRIMARY KEY(GuestID),
CONSTRAINT fk_GuestReservationID FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID),
CONSTRAINT fk_GuestRoomID FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

-- CREATE RESERVEDROOM
CREATE TABLE IF NOT EXISTS ReservedRoom
(ReservationID INT UNSIGNED,
RoomID SMALLINT UNSIGNED,
PRIMARY KEY(ReservationID,RoomID),
CONSTRAINT fk_ReservedReservationID FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID),
CONSTRAINT fk_ReservedRoomID FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

-- CREATE BILLSUMMARY
CREATE TABLE IF NOT EXISTS BillSummary
(BillID INT UNSIGNED AUTO_INCREMENT,
ReservationID INT UNSIGNED NOT NULL,
BillDate DATE NOT NULL,
Tax DECIMAL(5,2),
Total DECIMAL(15,2) NOT NULL,
PRIMARY KEY (BillID),
CONSTRAINT fk_BillReservationID FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID)
);

-- CEATE BILLDETAIL
CREATE TABLE IF NOT EXISTS BillDetail
(BillDetailID INT UNSIGNED AUTO_INCREMENT,
ReservationID INT UNSIGNED NOT NULL,
RoomID SMALLINT UNSIGNED NOT NULL,
BillDesc VARCHAR(30) NOT NULL,
Charge DECIMAL(7,2) NOT NULL,
Waive BOOL NOT NULL DEFAULT 0,
BillDate DATE NOT NULL,
PRIMARY KEY(BillDetailID),
CONSTRAINT fk_BillDetailReservationID FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID),
CONSTRAINT fk_BillDetailRoomID FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);